** PLEASE READ **
For some reason, the deployed version of the app on heroku has an H12 timeout error when
trying to access the stats. I documented the error on piazza like so:

My app fetches data from a python package api. This data is fetched on a page load which
takes very little time on local but for some reason I get an H12 error on Heroku every
time I try to go beyond the home page in the deployed version. This is strange to me because
the data I'm fetching is not large, at least not enough to warrant a >30 second response
time, so I'm really confused on why this is happening as these pages load super quick on
local even though the api call response time shouldn't vary that much.
 
The app builds and deploys just fine. Here are the Heroku logs:

2024-12-09T05:42:20.570374+00:00 heroku[router]: at=error code=H12 desc="Request timeout"
method=GET path="/nba_stats/player/1628973/" host=mini-fb-3c30967d650d.herokuapp.com
request_id=b79ae7d9-5c71-426e-b75b-9d824d04383d fwd="104.28.39.31" dyno=web.1
connect=0ms service=30000ms status=503 bytes=0 protocol=https

Edit:
I met with professor Stevens today and we found out that the reason for this error is that
the python package scrapes data from the NBA website and the NBA website has some sort of 
protection that blocks requests from being made from a 3rd party server. We tried getting the 
app deployed on the bu cs web apps site so we'll see how that goes once he talks to a system
admin about getting the right packages on there. Basically, he is aware of the situation and 
said to me that if graders come to him about he'll know what's going on.

To run the file locally, simply create a .env with the following variables:

SECRET_KEY= '-qp=r6bm3sepdm$32=wozf8!b9dl(9i3p%051t^!8e=_i=2h!-'
DEBUG=False
ENVIRONMENT=development
DATABASE_URL=sqlite:///db.sqlite3


The url will be http://127.0.0.1:8000/nba_stats/